/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.RegistroJugador;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Jugador;

/**
 *
 * @author Orion
 */
public class Form_AgregarJugador extends javax.swing.JFrame {

    /**
     * Creates new form Form_AgregarJugador
     */
    public Form_AgregarJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jText_RutJugador = new javax.swing.JTextField();
        jLabel_Rut1 = new javax.swing.JLabel();
        jText_DVJugador = new javax.swing.JTextField();
        jLabel_Nombre1 = new javax.swing.JLabel();
        jLabel_ApellidoPaterno1 = new javax.swing.JLabel();
        jLabel_ApellidoMaterno1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NombreJugador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jText_Appaterno = new javax.swing.JTextField();
        jText_Apmaterno = new javax.swing.JTextField();
        jText_Telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jText_FecNacDia = new javax.swing.JTextField();
        jText_FecNacMes = new javax.swing.JTextField();
        jText_FecNacAnio = new javax.swing.JTextField();
        jButton_Enviar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel_TituloRegistrarSocio1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_Posicion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Division = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 400));

        jText_RutJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_RutJugadorActionPerformed(evt);
            }
        });

        jLabel_Rut1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel_Rut1.setText("Rut");

        jText_DVJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_DVJugadorActionPerformed(evt);
            }
        });

        jLabel_Nombre1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel_Nombre1.setText("Nombre");

        jLabel_ApellidoPaterno1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel_ApellidoPaterno1.setText("Apellido Paterno ");

        jLabel_ApellidoMaterno1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel_ApellidoMaterno1.setText("Apellido Materno");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono");

        jTextField_NombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreJugadorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("Posición");

        jText_Appaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_AppaternoActionPerformed(evt);
            }
        });

        jText_Apmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ApmaternoActionPerformed(evt);
            }
        });

        jText_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_TelefonoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("Fecha Nacimiento");

        jText_FecNacDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_FecNacDia.setText("DD");
        jText_FecNacDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_FecNacDiaActionPerformed(evt);
            }
        });

        jText_FecNacMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_FecNacMes.setText("MM");
        jText_FecNacMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_FecNacMesActionPerformed(evt);
            }
        });

        jText_FecNacAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_FecNacAnio.setText("AAAA");
        jText_FecNacAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_FecNacAnioActionPerformed(evt);
            }
        });

        jButton_Enviar.setText("Enviar");
        jButton_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnviarActionPerformed(evt);
            }
        });

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jLabel_TituloRegistrarSocio1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_TituloRegistrarSocio1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel_TituloRegistrarSocio1.setText("Registrar Plantel");

        jLabel9.setText("-");

        jLabel10.setText("/");

        jLabel11.setText("/");

        jComboBox_Posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Definir", "Entrenador", "Portero", "Defensa", "Centro", "Delantero" }));
        jComboBox_Posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PosicionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setText("División");

        jComboBox_Division.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Definir", "Cuarta Infantil", "Tercera Infantil", "Segunda Infantil", "Primera Infantil", "Juvenil", "Tercera Adulto", "Segunda Adulto", "Primera Adulto", "Senior 35", "Senior 45", "Senior 55", "Damas" }));
        jComboBox_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DivisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel_TituloRegistrarSocio1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_Enviar)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton_Salir)
                                        .addGap(81, 81, 81))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jText_FecNacDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jText_FecNacMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jText_FecNacAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jComboBox_Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jText_Telefono)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_Rut1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jText_RutJugador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_DVJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_ApellidoMaterno1)
                                            .addComponent(jLabel_Nombre1))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jTextField_NombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jText_Apmaterno))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel_ApellidoPaterno1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jText_Appaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(121, 121, 121))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_TituloRegistrarSocio1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jText_RutJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText_DVJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel_Rut1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre1)
                    .addComponent(jTextField_NombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ApellidoPaterno1)
                    .addComponent(jText_Appaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ApellidoMaterno1)
                    .addComponent(jText_Apmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jText_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jText_FecNacDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jText_FecNacMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jText_FecNacAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Enviar)
                    .addComponent(jButton_Salir))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_RutJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_RutJugadorActionPerformed
        this.jText_RutJugador.setText("");
    }//GEN-LAST:event_jText_RutJugadorActionPerformed

    private void jTextField_NombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreJugadorActionPerformed
        this.jTextField_NombreJugador.setText("");
    }//GEN-LAST:event_jTextField_NombreJugadorActionPerformed

    private void jText_AppaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_AppaternoActionPerformed
        this.jText_Appaterno.setText("");
    }//GEN-LAST:event_jText_AppaternoActionPerformed

    private void jText_ApmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ApmaternoActionPerformed
        this.jText_Apmaterno.setText("");
    }//GEN-LAST:event_jText_ApmaternoActionPerformed

    private void jText_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_TelefonoActionPerformed
        this.jText_Telefono.setText("");
    }//GEN-LAST:event_jText_TelefonoActionPerformed

    private void jText_FecNacDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_FecNacDiaActionPerformed
        this.jText_FecNacDia.setText("");
    }//GEN-LAST:event_jText_FecNacDiaActionPerformed

    private void jText_FecNacMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_FecNacMesActionPerformed
        this.jText_FecNacMes.setText("");
    }//GEN-LAST:event_jText_FecNacMesActionPerformed

    private void jText_FecNacAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_FecNacAnioActionPerformed
        this.jText_FecNacAnio.setText("");
    }//GEN-LAST:event_jText_FecNacAnioActionPerformed

    private void jButton_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnviarActionPerformed
        String dv,nombre,appaterno,apmaterno,posicion,division,dia,mes,anio,fechaStr;
        Date fecha;
        int rut, telefono;
 
        
        try {
            rut = Integer.parseInt(this.jText_RutJugador.getText());
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "El Rut debe ser numérico", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_RutJugador.requestFocus();
            return;
        }
        
        dv = this.jText_DVJugador.getText();
        if (dv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese DV", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_DVJugador.requestFocus();
            return;
        }
        
        nombre = this.jTextField_NombreJugador.getText();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Nombre", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jTextField_NombreJugador.requestFocus();
            return;
        }
        
        appaterno = this.jText_Appaterno.getText();
        if (appaterno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Apellido Paterno", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_Appaterno.requestFocus();
            return;
        }
        
        apmaterno = this.jText_Apmaterno.getText();
        if (apmaterno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Apellido Materno", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_Apmaterno.requestFocus();
            return;
        }
        
        try {
            telefono = Integer.parseInt(this.jText_Telefono.getText());
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "El Teléfono debe ser numérico", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_Telefono.requestFocus();
            return;
        }
        
        posicion = this.jComboBox_Posicion.getSelectedItem().toString();
        division = this.jComboBox_Division.getSelectedItem().toString();
        
        dia = this.jText_FecNacDia.getText();
        mes = this.jText_FecNacMes.getText();
        anio = this.jText_FecNacAnio.getText();
        
        if (dia.isEmpty() || mes.isEmpty() || anio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Fecha", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_FecNacDia.requestFocus();
            return;
        }
        
        fechaStr = dia + "/" + mes +"/" + anio;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            fecha = formato.parse(fechaStr);
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "La Fecha debe ser dd/mm/aaaa", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jText_FecNacDia.requestFocus();
            return;
        }
 
        Jugador jugador = new Jugador(0,posicion, fecha, division, 0, rut, dv, nombre, appaterno, apmaterno,telefono);
        
        RegistroJugador reg = new RegistroJugador();
        
        try {
            if (reg.buscarPorCod(jugador.getCodJugador()).getpNombre()== null) {
                if (reg.agregar(jugador)) {
                    JOptionPane.showMessageDialog(this, "Se agrego al Plantel satisfactoriamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "NO Se agrego al plantel ", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "El miembro del plantel ya existe", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Form_AgregarSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_EnviarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jText_DVJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_DVJugadorActionPerformed
        this.jText_DVJugador.setText("");
    }//GEN-LAST:event_jText_DVJugadorActionPerformed

    private void jComboBox_PosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PosicionActionPerformed
        this.jComboBox_Posicion.getSelectedItem();
    }//GEN-LAST:event_jComboBox_PosicionActionPerformed

    private void jComboBox_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DivisionActionPerformed
        this.jComboBox_Division.getSelectedItem();
    }//GEN-LAST:event_jComboBox_DivisionActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_AgregarJugador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Enviar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JComboBox<String> jComboBox_Division;
    private javax.swing.JComboBox<String> jComboBox_Posicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ApellidoMaterno1;
    private javax.swing.JLabel jLabel_ApellidoPaterno1;
    private javax.swing.JLabel jLabel_Nombre1;
    private javax.swing.JLabel jLabel_Rut1;
    private javax.swing.JLabel jLabel_TituloRegistrarSocio1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_NombreJugador;
    private javax.swing.JTextField jText_Apmaterno;
    private javax.swing.JTextField jText_Appaterno;
    private javax.swing.JTextField jText_DVJugador;
    private javax.swing.JTextField jText_FecNacAnio;
    private javax.swing.JTextField jText_FecNacDia;
    private javax.swing.JTextField jText_FecNacMes;
    private javax.swing.JTextField jText_RutJugador;
    private javax.swing.JTextField jText_Telefono;
    // End of variables declaration//GEN-END:variables
}
