/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Orion
 */
public class Form_AgregarPartido extends javax.swing.JFrame {

    /**
     * Creates new form Form_AgregarPartido
     */
    public Form_AgregarPartido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Lugar = new javax.swing.JLabel();
        jLabel_Rival = new javax.swing.JLabel();
        jLabel_Dia = new javax.swing.JLabel();
        jLabel_Estado = new javax.swing.JLabel();
        jtext_Rival = new javax.swing.JTextField();
        jText_Dia = new javax.swing.JTextField();
        jText_Mes = new javax.swing.JTextField();
        jText_Lugar = new javax.swing.JTextField();
        jText_Titulo = new javax.swing.JTextField();
        jText_Anno = new javax.swing.JTextField();
        jLabel_mes = new javax.swing.JLabel();
        jComboBox_EstadoPartido = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton_IngresaDetallesPartido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel_Lugar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel_Lugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Lugar.setText("Lugar ");

        jLabel_Rival.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel_Rival.setText("Rival");

        jLabel_Dia.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel_Dia.setText("Dia");

        jLabel_Estado.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_Estado.setText("Estado");

        jText_Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_DiaActionPerformed(evt);
            }
        });

        jText_Lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_LugarActionPerformed(evt);
            }
        });

        jText_Titulo.setBackground(new java.awt.Color(0, 0, 0));
        jText_Titulo.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jText_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jText_Titulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_Titulo.setText("Ingresar Partido");
        jText_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_TituloActionPerformed(evt);
            }
        });

        jLabel_mes.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_mes.setText("Mes");

        jComboBox_EstadoPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Jugar", "Cancelado", "Jugado" }));
        jComboBox_EstadoPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EstadoPartidoActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");

        jButton_IngresaDetallesPartido.setText("Ingresar detalles del partido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Lugar)
                            .addComponent(jLabel_Rival)
                            .addComponent(jLabel_Dia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtext_Rival)
                            .addComponent(jText_Lugar)
                            .addComponent(jComboBox_EstadoPartido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jText_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_mes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jText_Anno, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 131, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton_IngresaDetallesPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jText_Titulo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jText_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_Lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Rival)
                    .addComponent(jtext_Rival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Dia)
                    .addComponent(jText_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_mes)
                    .addComponent(jText_Anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_EstadoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton_IngresaDetallesPartido))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_DiaActionPerformed

    private void jText_LugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_LugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_LugarActionPerformed

    private void jText_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TituloActionPerformed

    private void jComboBox_EstadoPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EstadoPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_EstadoPartidoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_AgregarPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_AgregarPartido().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_IngresaDetallesPartido;
    private javax.swing.JComboBox<String> jComboBox_EstadoPartido;
    private javax.swing.JLabel jLabel_Dia;
    private javax.swing.JLabel jLabel_Estado;
    private javax.swing.JLabel jLabel_Lugar;
    private javax.swing.JLabel jLabel_Rival;
    private javax.swing.JLabel jLabel_mes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jText_Anno;
    private javax.swing.JTextField jText_Dia;
    private javax.swing.JTextField jText_Lugar;
    private javax.swing.JTextField jText_Mes;
    private javax.swing.JTextField jText_Titulo;
    private javax.swing.JTextField jtext_Rival;
    // End of variables declaration//GEN-END:variables
}
